env:
  global:
    - LC_CTYPE=en_US.UTF-8
before_install:
  - brew update
  - brew install swiftlint
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode7.3
script: 
  - pod lib lint --allow-warnings
  - swiftlint
  - ./run_tests ios
  - ./run_tests osx
  - ./run_tests tvos
after_success:
  - bash <(curl -s https://codecov.io/bash)
